import { EventNameMap } from "./maps";

/**
 * @summary
 * An exhaustive list of `eventname`-`onevenetname` pairs.
 */
export type EventNames =
  | EventNameMap<"abort", "onabort">
  | EventNameMap<"animationcancel", "onanimationcancel">
  | EventNameMap<"animationend", "onanimationend">
  | EventNameMap<"animationiteration", "onanimationiteration">
  | EventNameMap<"animationstart", "onanimationstart">
  | EventNameMap<"auxclick", "onauxclick">
  | EventNameMap<"blur", "onblur">
  | EventNameMap<"cancel", "oncancel">
  | EventNameMap<"canplay", "oncanplay">
  | EventNameMap<"canplaythrough", "oncanplaythrough">
  | EventNameMap<"change", "onchange">
  | EventNameMap<"click", "onclick">
  | EventNameMap<"close", "onclose">
  | EventNameMap<"contextmenu", "oncontextmenu">
  | EventNameMap<"copy", "oncopy">
  | EventNameMap<"cuechange", "oncuechange">
  | EventNameMap<"cut", "oncut">
  | EventNameMap<"fullscreenchange", "onfullscreenchange">
  | EventNameMap<"fullscreenerror", "onfullscreenerror">
  | EventNameMap<"paste", "onpaste">
  | EventNameMap<"pointerlockchange", "onpointerlockchange">
  | EventNameMap<"pointerlockerror", "onpointerlockerror">
  | EventNameMap<"visibilitychange", "onvisibilitychange">
  | EventNameMap<"dblclick", "ondblclick">
  | EventNameMap<"drag", "ondrag">
  | EventNameMap<"dragend", "ondragend">
  | EventNameMap<"dragenter", "ondragenter">
  | EventNameMap<"dragexit", "ondragexit">
  | EventNameMap<"dragleave", "ondragleave">
  | EventNameMap<"dragover", "ondragover">
  | EventNameMap<"dragstart", "ondragstart">
  | EventNameMap<"drop", "ondrop">
  | EventNameMap<"afterprint", "onafterprint">
  | EventNameMap<"beforeprint", "onbeforeprint">
  | EventNameMap<"beforeunload", "onbeforeunload">
  | EventNameMap<"compassneedscalibration", "oncompassneedscalibration">
  | EventNameMap<"durationchange", "ondurationchange">
  | EventNameMap<"emptied", "onemptied">
  | EventNameMap<"ended", "onended">
  | EventNameMap<"error", "onerror">
  | EventNameMap<"focus", "onfocus">
  | EventNameMap<"focusin", "onfocusin">
  | EventNameMap<"focusout", "onfocusout">
  | EventNameMap<"gotpointercapture", "ongotpointercapture">
  | EventNameMap<"input", "oninput">
  | EventNameMap<"invalid", "oninvalid">
  | EventNameMap<"keydown", "onkeydown">
  | EventNameMap<"keypress", "onkeypress">
  | EventNameMap<"keyup", "onkeyup">
  | EventNameMap<"load", "onload">
  | EventNameMap<"loadeddata", "onloadeddata">
  | EventNameMap<"loadedmetadata", "onloadedmetadata">
  | EventNameMap<"loadstart", "onloadstart">
  | EventNameMap<"lostpointercapture", "onlostpointercapture">
  | EventNameMap<"mousedown", "onmousedown">
  | EventNameMap<"mouseenter", "onmouseenter">
  | EventNameMap<"mouseleave", "onmouseleave">
  | EventNameMap<"mousemove", "onmousemove">
  | EventNameMap<"mouseout", "onmouseout">
  | EventNameMap<"mouseover", "onmouseover">
  | EventNameMap<"mouseup", "onmouseup">
  | EventNameMap<"hashchange", "onhashchange">
  | EventNameMap<"pointercancel", "onpointercancel">
  | EventNameMap<"pointerdown", "onpointerdown">
  | EventNameMap<"pointerenter", "onpointerenter">
  | EventNameMap<"pointerleave", "onpointerleave">
  | EventNameMap<"pointermove", "onpointermove">
  | EventNameMap<"pointerout", "onpointerout">
  | EventNameMap<"pointerover", "onpointerover">
  | EventNameMap<"pointerup", "onpointerup">
  | EventNameMap<"ratechange", "onratechange">
  | EventNameMap<"reset", "onreset">
  | EventNameMap<"resize", "onresize">
  | EventNameMap<"scroll", "onscroll">
  | EventNameMap<"securitypolicyviolation", "onsecuritypolicyviolation">
  | EventNameMap<"seeked", "onseeked">
  | EventNameMap<"seeking", "onseeking">
  | EventNameMap<"select", "onselect">
  | EventNameMap<"selectionchange", "onselectionchange">
  | EventNameMap<"selectstart", "onselectstart">
  | EventNameMap<"stalled", "onstalled">
  | EventNameMap<"submit", "onsubmit">
  | EventNameMap<"suspend", "onsuspend">
  | EventNameMap<"timeupdate", "ontimeupdate">
  | EventNameMap<"toggle", "ontoggle">
  | EventNameMap<"touchcancel", "ontouchcancel">
  | EventNameMap<"touchend", "ontouchend">
  | EventNameMap<"touchmove", "ontouchmove">
  | EventNameMap<"touchstart", "ontouchstart">
  | EventNameMap<"transitioncancel", "ontransitioncancel">
  | EventNameMap<"transitionend", "ontransitionend">
  | EventNameMap<"transitionrun", "ontransitionrun">
  | EventNameMap<"transitionstart", "ontransitionstart">
  | EventNameMap<"volumechange", "onvolumechange">
  | EventNameMap<"waiting", "onwaiting">
  | EventNameMap<"wheel", "onwheel">
  | EventNameMap<"devicelight", "ondevicelight">
  | EventNameMap<"devicemotion", "ondevicemotion">
  | EventNameMap<"deviceorientation", "ondeviceorientation">
  | EventNameMap<"deviceorientationabsolute", "ondeviceorientationabsolute">
  | EventNameMap<"message", "onmessage">
  | EventNameMap<"mousewheel", "onmousewheel">
  | EventNameMap<"MSGestureChange", "onmsgesturechange">
  | EventNameMap<"MSGestureDoubleTap", "onmsgesturedoubletap">
  | EventNameMap<"MSGestureEnd", "onmsgestureend">
  | EventNameMap<"MSGestureHold", "onmsgesturehold">
  | EventNameMap<"MSGestureStart", "onmsdgesturestart">
  | EventNameMap<"MSGestureTap", "onmsgesturetap">
  | EventNameMap<"MSInertiaStart", "onmsinertiastart">
  | EventNameMap<"MSPointerCancel", "onmspointercancel">
  | EventNameMap<"MSPointerDown", "onmspointerdown">
  | EventNameMap<"MSPointerEnter", "onmspointerlnter">
  | EventNameMap<"MSPointerLeave", "onmspointerleave">
  | EventNameMap<"MSPointerMove", "onmspointermove">
  | EventNameMap<"MSPointerOut", "onmspointerout">
  | EventNameMap<"MSPointerOver", "onmspointerover">
  | EventNameMap<"MSPointerUp", "onmspointerup">
  | EventNameMap<"offline", "onoffline">
  | EventNameMap<"online", "ononline">
  | EventNameMap<"orientationchange", "onorientationchange">
  | EventNameMap<"pagehide", "onpagehide">
  | EventNameMap<"pageshow", "onpageshow">
  | EventNameMap<"pause", "onpause">
  | EventNameMap<"play", "onplay">
  | EventNameMap<"playing", "onplaying">
  | EventNameMap<"popstate", "onpopstate">
  | EventNameMap<"storage", "onstorage">
  | EventNameMap<"unload", "onunload">
  | EventNameMap<"vrdisplayactivate", "onvrdisplayactivate">
  | EventNameMap<"vrdisplayblur", "onvrdisplayblur">
  | EventNameMap<"vrdisplayconnect", "onvrdisplayconnect">
  | EventNameMap<"vrdisplaydeactivate", "onvrdisplaydeactivate">
  | EventNameMap<"vrdisplaydisconnect", "onvrdisplaydisconnect">
  | EventNameMap<"vrdisplayfocus", "onvrdisplayfocus">
  | EventNameMap<"vrdisplaypointerrestricted", "onvrdisplaypointerrestricted">
  | EventNameMap<
      "vrdisplaypointerunrestricted",
      "onvrdisplaypointerunrestricted"
    >
  | EventNameMap<"vrdisplaypresentchange", "onvrdisplaypresentchange">
  | EventNameMap<"languagechange", "onlanguagechange">
  | EventNameMap<"messageerror", "onmessageerror">
  | EventNameMap<"rejectionhandled", "onrejectionhandled">
  | EventNameMap<"unhandledrejection", "onunhandledrejection">
  | EventNameMap<"readystatechange", "onreadystatechange">
  | EventNameMap<"progress", "onprogress">;
